# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voice_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13voice_service.proto\x12\x05voice\"\x07\n\x05\x45mpty\"5\n\x11RecordingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"O\n\x0eStatusResponse\x12\x14\n\x0cis_recording\x18\x01 \x01(\x08\x12\x14\n\x0c\x64\x65vice_state\x18\x02 \x01(\t\x12\x11\n\tconnected\x18\x03 \x01(\x08\"p\n\x0cStatusUpdate\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tconnected\x18\x02 \x01(\x08\x12\x14\n\x0cis_recording\x18\x03 \x01(\x08\x12\x14\n\x0c\x64\x65vice_state\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"<\n\x0bTextMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\xa8\x02\n\x0cVoiceService\x12\x38\n\x0eStartRecording\x12\x0c.voice.Empty\x1a\x18.voice.RecordingResponse\x12\x37\n\rStopRecording\x12\x0c.voice.Empty\x1a\x18.voice.RecordingResponse\x12\x30\n\tGetStatus\x12\x0c.voice.Empty\x1a\x15.voice.StatusResponse\x12\x36\n\x0fSubscribeStatus\x12\x0c.voice.Empty\x1a\x13.voice.StatusUpdate0\x01\x12;\n\x15SubscribeTextMessages\x12\x0c.voice.Empty\x1a\x12.voice.TextMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_RECORDINGRESPONSE']._serialized_start=39
  _globals['_RECORDINGRESPONSE']._serialized_end=92
  _globals['_STATUSRESPONSE']._serialized_start=94
  _globals['_STATUSRESPONSE']._serialized_end=173
  _globals['_STATUSUPDATE']._serialized_start=175
  _globals['_STATUSUPDATE']._serialized_end=287
  _globals['_TEXTMESSAGE']._serialized_start=289
  _globals['_TEXTMESSAGE']._serialized_end=349
  _globals['_VOICESERVICE']._serialized_start=352
  _globals['_VOICESERVICE']._serialized_end=648
# @@protoc_insertion_point(module_scope)
